Repository Calculadora-do-Agricultor/calculadora-do-agricultor-front, pull requests merged in 2025-06, with the labels that each got.

#309 Refatorar animações e botões confusos nos painéis de métricas
  src/components/LogCard/index.jsx
  src/components/MetricCard/index.jsx
  src/components/MetricsToggle/MetricsToggle.jsx
  src/pages/LogsManagement/index.jsx
  src/pages/UserManagement/UserManagement.css
  src/pages/UserManagement/index.jsx
Labels: dw-task

#316 feat: implementar sistema completo de glossário com favoritos e busca
  package-lock.json
  package.json
  src/App.jsx
  src/components/GlossaryExample/index.jsx
  src/components/GlossarySearch/index.jsx
  src/components/Navbar/components/MobileMenu.jsx
  src/components/Navbar/components/NavLinks.jsx
  src/components/ui/GlossaryTerm.jsx
  src/data/glossary.js
  src/hooks/useGlossary.js
  src/pages/Glossario/index.jsx
Labels: enhancement

#298 Criar página "Meu Perfil" com edição de dados do usuário
  package-lock.json
  package.json
  src/pages/Login/Login.jsx
  src/pages/Settings/Settings.jsx
Labels: dw-task

#322 fix:corrige contagem de visualizações dos cálculos
  src/components/CalculationList/index.jsx
  src/components/CalculationModal/index.jsx
Labels: bug

#305 Implementação do hook useParametrosFormulario
  src/components/CalculationList/index.jsx
  src/components/CalculationModal/index.jsx
  src/components/CalculationResult/index.jsx
  src/components/CalculationResult/style.css
  src/components/EmptyState/EmptyState.jsx
  src/components/EmptyState/styles.css
  src/components/ExpressionValidator/index.jsx
  src/components/ExpressionValidator/styles.css
  src/hooks/useCalculationResult.jsx
  src/hooks/useFormParameters.jsx
  src/utils/mathEvaluator.js
Labels: enhancement

#315 Adicionado sistema de verificação de integridade de dados
  src/App.jsx
  src/components/CalculationList/index.jsx
  src/components/DataIntegrityReport/index.jsx
  src/components/DataIntegrityReport/styles.css
  src/components/Navbar/components/MobileMenu.jsx
  src/components/Navbar/components/NavLinks.jsx
  src/hooks/useDataIntegrityCheck.js
  src/hooks/useOptimizedFirestore.js
  src/pages/Calculator/Calculator.jsx
  src/pages/DataIntegrityPage/index.jsx
  src/pages/index.js
Labels: enhancement

#320 Criar fallback automático para falhas de rede ou Firebase
  src/App.jsx
  src/components/CalculationActions/index.jsx
  src/components/CalculationList/index.jsx
  src/components/Categories/index.jsx
  src/components/CategoryActions/index.jsx
  src/components/Navbar/components/MobileMenu.jsx
  src/components/Navbar/components/NavLinks.jsx
  src/components/Navbar/index.jsx
  src/components/PrivateRoute/index.jsx
  src/components/ProtectedRoute/index.jsx
  src/context/AdminContext.jsx
  src/context/AuthContext.jsx
  src/context/useAdmin.js
  src/main.jsx
  src/pages/Calculator/Calculator.jsx
  src/pages/Dashboard/index.jsx
  src/pages/Login/Login.jsx
  src/pages/LogsManagement/index.jsx
  src/pages/Register/Register.jsx
  src/pages/Settings/Settings.jsx
  src/pages/UserManagement/index.jsx
  src/services/firebaseConfig.js
  src/services/firebaseWrapper.js
Labels: dw-task

#323 Entrega de mais tasks de DW3
  package-lock.json
  package.json
  src/App.jsx
  src/components/CalculationActions/index.jsx
  src/components/CalculationList/index.jsx
  src/components/CalculationModal/index.jsx
  src/components/CalculationModal/styles.css
  src/components/CalculationResult/index.jsx
  src/components/CalculationResult/style.css
  src/components/Categories/index.jsx
  src/components/CategoryActions/index.jsx
  src/components/CreateCalculation/index.jsx
  src/components/CreateCalculation/styles.css
  src/components/DataIntegrityReport/index.jsx
  src/components/DataIntegrityReport/styles.css
  src/components/EditCalculation/index.jsx
  src/components/EditCalculation/styles.css
  src/components/EmptyState/EmptyState.jsx
  src/components/EmptyState/styles.css
  src/components/ExpressionValidator/index.jsx
  src/components/ExpressionValidator/styles.css
  src/components/MetricsToggle/index.jsx
  src/components/Navbar/components/MobileMenu.jsx
  src/components/Navbar/components/NavLinks.jsx
  src/components/Navbar/index.jsx
  src/components/PrivateRoute/index.jsx
  src/components/ProtectedRoute/index.jsx
  src/components/index.js
  src/components/ui/EmptyState.jsx
  src/components/ui/EmptyState/index.jsx
  src/components/ui/Toast.jsx
  src/components/ui/index.js
  src/context/AuthContext.jsx
  src/context/ToastContext.jsx
  src/hooks/useCalculationResult.jsx
  src/hooks/useDataIntegrityCheck.js
  src/hooks/useFormParameters.jsx
  src/hooks/useOptimizedFirestore.js
  src/hooks/useToast.js
  src/main.jsx
  src/pages/Calculator/Calculator.jsx
  src/pages/Dashboard/index.jsx
  src/pages/DataIntegrityPage/index.jsx
  src/pages/Login/Login.jsx
  src/pages/LogsManagement/index.jsx
  src/pages/MathJsDemoPage/styles.css
  src/pages/Register/Register.jsx
  src/pages/Settings/Settings.jsx
  src/pages/index.js
  src/services/firebaseConfig.js
  src/services/firebaseWrapper.js
  src/utils/mathEvaluator.js
  vite.config.js
Labels: dw-task

#324 Implementação do componente CategoryCard
  src/App.jsx
  src/components/CalculationModal/ExampleUsage.jsx
  src/components/CalculationModal/README.md
  src/components/CategoriaCard/index.js
  src/components/CategoriaCard/index.jsx
  src/components/Categories/index.jsx
  src/components/CreateCategory/index.jsx
  src/components/EditCategory/index.jsx
  src/components/index.js
  src/components/ui/EmptyState.jsx
  src/hooks/useFetchDocuments.jsx
  src/pages/Calculator/Calculator.css
  src/pages/Calculator/Calculator.jsx
  vite.config.js
Labels: enhancement, dw-task, refactor

#326 Develop
  .firebaserc
  firestore.indexes.json
  funcionou.txt
  package-lock.json
  package.json
  src/App.jsx
  src/components/CalculationActions/index.jsx
  src/components/CalculationHistoryModal/index.jsx
  src/components/CalculationModal/ExampleUsage.jsx
  src/components/CalculationModal/README.md
  src/components/CalculationModal/index.jsx
  src/components/CalculationModal/styles.css
  src/components/CategoriaCard/index.js
  src/components/CategoriaCard/index.jsx
  src/components/Categories/index.jsx
  src/components/CreateCategory/index.jsx
  src/components/EditCategory/index.jsx
  src/components/index.js
  src/components/ui/EmptyState.jsx
  src/components/ui/dialog.jsx
  src/components/ui/dropdown-menu-calculation/index.jsx
  src/components/ui/dropdown-menu.jsx
  src/components/ui/scroll-area.jsx
  src/hooks/useCalculationHistoryCleanup.js
  src/hooks/useFetchDocuments.jsx
  src/pages/Calculator/Calculator.css
  src/pages/Calculator/Calculator.jsx
  src/services/calculationHistoryService.js
  src/tests/calculationHistory.test.js
  src/tests/setup.js
  vite.config.js
  vitest.config.js
Labels: dw-task

#327 Feat/faq ajuda documentada
  package-lock.json
  src/App.jsx
  src/components/ConfirmDialog/index.jsx
  src/components/LoadingSpinner/index.jsx
  src/components/Navbar/components/MobileMenu.jsx
  src/components/Navbar/components/NavLinks.jsx
  src/context/AuthContext.jsx
  src/hooks/useFAQ.js
  src/pages/Admin/FAQAdmin/FAQItemModal.jsx
  src/pages/Admin/FAQAdmin/index.jsx
  src/pages/FAQ/FAQ.jsx
  src/pages/FAQ/index.js
  src/pages/Settings/Settings.jsx
  src/pages/index.js
  src/services/faqService.js
  src/services/firebaseWrapper.js
Labels: enhancement, dw-task

#328 Develop to Homologation
  package-lock.json
  src/App.jsx
  src/components/ConfirmDialog/index.jsx
  src/components/LoadingSpinner/index.jsx
  src/components/Navbar/components/MobileMenu.jsx
  src/components/Navbar/components/NavLinks.jsx
  src/context/AuthContext.jsx
  src/hooks/useFAQ.js
  src/pages/Admin/FAQAdmin/FAQItemModal.jsx
  src/pages/Admin/FAQAdmin/index.jsx
  src/pages/FAQ/FAQ.jsx
  src/pages/FAQ/index.js
  src/pages/Settings/Settings.jsx
  src/pages/index.js
  src/services/faqService.js
  src/services/firebaseWrapper.js
Labels: documentation, enhancement

#329 Develop
  package-lock.json
  package.json
  src/components/Categories/index.jsx
  src/components/ConfirmDialog/index.jsx
  src/pages/Admin/FAQAdmin/FAQItemModal.jsx
  src/pages/Admin/FAQAdmin/index.jsx
  src/pages/FAQ/FAQ.jsx
  src/pages/Register/Register.jsx
  src/services/firebaseConfig.js
Labels: bug

#332 Feat/service save formula secure
  firestore.rules
  src/components/FormulaManager/index.jsx
  src/components/FormulaManager/styles.css
  src/components/FormulaPreviewModal/index.jsx
  src/hooks/useCalculationResult.jsx
  src/hooks/useFormulaService.js
  src/services/README.md
  src/services/__tests__/formulaService.test.js
  src/services/formulaService.js
Labels: enhancement, dw-task

#335 refactor: improve error handling and add missing React imports
  src/components/CalculationList/index.jsx
  src/components/CreateCalculation/index.jsx
  src/components/EditCalculation/index.jsx
  src/components/FormulaManager/index.jsx
  src/components/TermsOfUseModal/index.jsx
  src/context/AuthContext.jsx
  src/main.jsx
  src/pages/Calculator/Calculator.jsx
  src/pages/Dashboard/index.jsx
  src/pages/Login/Login.jsx
  src/pages/Register/Register.jsx
  src/pages/Settings/Settings.jsx
  src/services/firebaseWrapper.js
Labels: bug
